// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpfcYGBxDAJLOS1alNkd9wnNVY1qEJOTc',
    appId: '1:378067613328:web:ecabb808f95594928c4a15',
    messagingSenderId: '378067613328',
    projectId: 'ecommerce-3342c',
    authDomain: 'ecommerce-3342c.firebaseapp.com',
    storageBucket: 'ecommerce-3342c.firebasestorage.app',
    measurementId: 'G-KEXD7MWD4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-uD7d7PA9YCryhs_7dRmlP9UQ3ukATVo',
    appId: '1:378067613328:android:647b39eeb72cdf0b8c4a15',
    messagingSenderId: '378067613328',
    projectId: 'ecommerce-3342c',
    storageBucket: 'ecommerce-3342c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABlZ7BnDPxOoAl7aXjsxN_UtTj14dwR8Y',
    appId: '1:378067613328:ios:fea212ad3d9d6b348c4a15',
    messagingSenderId: '378067613328',
    projectId: 'ecommerce-3342c',
    storageBucket: 'ecommerce-3342c.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABlZ7BnDPxOoAl7aXjsxN_UtTj14dwR8Y',
    appId: '1:378067613328:ios:fea212ad3d9d6b348c4a15',
    messagingSenderId: '378067613328',
    projectId: 'ecommerce-3342c',
    storageBucket: 'ecommerce-3342c.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpfcYGBxDAJLOS1alNkd9wnNVY1qEJOTc',
    appId: '1:378067613328:web:1fd938b4565946d98c4a15',
    messagingSenderId: '378067613328',
    projectId: 'ecommerce-3342c',
    authDomain: 'ecommerce-3342c.firebaseapp.com',
    storageBucket: 'ecommerce-3342c.firebasestorage.app',
    measurementId: 'G-W4G01TVEZS',
  );
}
